runtime: python39
entrypoint: gunicorn -b :$PORT -w 2 main:app
service: indus-app
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

